### ISSUE TITLE
Error upon start

### ISSUE THREAD

**Issue by Discord-Verified-Developer** [zachariapopcorn/rbx-manager#21]
Hey there keep getting this breaking error. Hoping you could figure out what's causing it. 
![Screenshot_20230421-124657_Replit](https://user-images.githubusercontent.com/98547040/233727138-e59de415-f5e9-4f70-9612-427cd9462b1f.jpg)

**Comment by xSifat** [comment]
Use node.js instead of Typescript.

https://ibb.co/Hnj416G

**Comment by xSifat** [comment]
The [Guide](https://devforum.roblox.com/t/rbxmanager-simple-roblox-group-and-game-management-bot-ranking-and-moderation-bot/2170984) provides instructions on how to set up and place the files in their appropriate locations.

**Comment by zachariapopcorn** [comment]
@Discord-Verified-Developer Use Nix (aka Blank Repl). If you followed the guide you would've done this
