### ISSUE TITLE
Error using login command

### ISSUE THREAD

**Issue by itzheropvp** [zachariapopcorn/rbx-manager#22]
While using the command /login and with success doing the captcha the command throw an error and the console sent this.

```
TypeError: Cannot read properties of undefined (reading '0')
    at Object.run (/home/runner/rbx-manager/build/commands/group/general/login.js:173:166)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BotClient.<anonymous> (/home/runner/rbx-manager/build/index.js:162:23)
```

**Comment by zachariapopcorn** [comment]
Can you send what the bot sent?

**Comment by zachariapopcorn** [comment]
I have no issues with the login command

**Comment by itzheropvp** [comment]
I fixed by doing it manually using a proxy. The bot was sending a success message and after that sent an embed saying "There was an error while trying to run this command. The error has been logged in the console".

**Comment by itzheropvp** [comment]
After this i don't know why the bot can't comunicate with the server. I setup correctly everything but idk doesn't work i will try some things

**Comment by zachariapopcorn** [comment]
I believe I fixed this in the dev branch. Once I'm done with the current update (v2.5) and merge into master try updating

**Comment by zachariapopcorn** [comment]
2.5 just got released, I'm gonna close this issue now. Please make a new one if you are still having issues
