### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by WavaDev** [zachariapopcorn/rbx-manager#29]
I have done npm install, and have done npm install fs. And i have tried to delete node_modules many times, and reinstall all of the packages.
![c5e013458d8612084614423431e2f1b82fdbbd98](https://user-images.githubusercontent.com/127393002/236511695-b0e32560-2b66-4214-9b47-4538d5e23878.png)

OS: Ubuntu
Version: I don’t remember.
Nodejs Version: v12.22.9

**Comment by zachariapopcorn** [comment]
Update node, you need node 18 to run this

**Comment by WavaDev** [comment]
![image](https://user-images.githubusercontent.com/127393002/236537293-62e1c1aa-49ce-40ec-9ccb-0b089fc1eabe.png)
How to fix this?
