### ISSUE TITLE
Console Script Error

### ISSUE THREAD

**Issue by SD-SapphireDevelopment** [zachariapopcorn/rbx-manager#37]
This error keeps occurring and I cant seem to fix it. 
![IMG_5982](https://github.com/zachariapopcorn/rbx-manager/assets/134190157/bc10887a-e979-48d4-ba5c-34853b0a44a7)

**Comment by zachariapopcorn** [comment]
I forgot ``InsertService:LoadAsset()`` needs you to own the thing, I'll push a fix
