### ISSUE TITLE
Yo (replit)

### ISSUE THREAD

**Issue by CodingWithChriss** [zachariapopcorn/rbx-manager#41]
This isn't working for me![image](https://github.com/zachariapopcorn/rbx-manager/assets/111544427/aa7f9fdd-b691-49bd-a28c-ee5652087528)

**Comment by CodingWithChriss** [comment]
@zachariapopcorn

**Comment by zachariapopcorn** [comment]
You didn't copy the replit file :/

**Comment by CodingWithChriss** [comment]
I didSent from my iPhoneOn Jun 5, 2023, at 1:45 PM, zachariapopcorn ***@***.***> wrote:﻿
You didn't copy the replit file :/

**Comment by zachariapopcorn** [comment]
As shown from the error, it tried to run the cowsay command, which is the default command configured in the replit file. You didn't replace it with the one in here
