### ISSUE TITLE
Can't run on REPLIT

### ISSUE THREAD

**Issue by Discord-Verified-Developer** [zachariapopcorn/rbx-manager#47]
The same error keeps occurring!  
![Screenshot 2023-10-08 184348](https://github.com/zachariapopcorn/rbx-manager/assets/98547040/499d8342-75c7-444a-9b0e-890e7aa953b2)

**Comment by zachariapopcorn** [comment]
I'm able to clone it just fine

**Comment by Discord-Verified-Developer** [comment]
I found out it was because I didn't have space left on replit. Regardless, next update can you add a remove warnings command?

**Comment by zachariapopcorn** [comment]
I'll put on the todo, but until I get any motivation to work on this again (excluding fixing bugs), it's on hold

**Comment by Discord-Verified-Developer** [comment]
I'm not sure if it's a bug but there is something wrong with the mute
command. When muting someone and trying to join the game you get kicked
because the mute command errors.

I'm not sure if you're able to look into it or not.
